function [ MF_type_para ] = decodeFRNN_MF( FRNNtype, indiv )
%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%EVO1_FRNN - fuzzy rough neural network
N_INPUT_EVO1_FRNN = 3;
N_OUTPUT_EVO1_FRNN = 1;
MAX_NUM_CLUSTER_EVO1_FRNN = 3;
MIN_NUM_CLUSTER_EVO1_FRNN = 1;
MAX_NUM_CLUSTER_MEM_PPARA_EVO1_FRNN = 9;
NUM_CLASS_EVO1_FRNN = 3;
MAX_NUM_FUZZY_RULE_EVO1_FRNN = (2 * N_INPUT_EVO1_FRNN + 1);
DIM_CLUSTER_BIN_RULE_EVO1_FRNN = (MAX_NUM_FUZZY_RULE_EVO1_FRNN * N_INPUT_EVO1_FRNN);
DIM_CLUSTER_MEM_EVO1_FRNN = (N_INPUT_EVO1_FRNN * MAX_NUM_CLUSTER_EVO1_FRNN);
DIM_CLUSTER_MEM_TYPE_EVO1_FRNN = DIM_CLUSTER_MEM_EVO1_FRNN;
DIM_CLUSTER_MEM_PARA_EVO1_FRNN = (MAX_NUM_CLUSTER_MEM_PPARA_EVO1_FRNN * DIM_CLUSTER_MEM_EVO1_FRNN);
DIM_FUZZY_BIN_ROUGH_EVO1_FRNN = (NUM_CLASS_EVO1_FRNN * MAX_NUM_FUZZY_RULE_EVO1_FRNN);
DIM_FUZZY_ROUGH_MEM_PARA_EVO1_FRNN = (NUM_CLASS_EVO1_FRNN * MAX_NUM_FUZZY_RULE_EVO1_FRNN);

DIM_EVO1_FRNN = (DIM_CLUSTER_MEM_TYPE_EVO1_FRNN + DIM_CLUSTER_BIN_RULE_EVO1_FRNN + DIM_FUZZY_BIN_ROUGH_EVO1_FRNN + DIM_CLUSTER_MEM_PARA_EVO1_FRNN + DIM_FUZZY_ROUGH_MEM_PARA_EVO1_FRNN + NUM_CLASS_EVO1_FRNN);
DIM_OBJ_EVO1_FRNN = 2;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%EVO2_FRNN - fuzzy rough neural network
N_INPUT_EVO2_FRNN = 3;
N_OUTPUT_EVO2_FRNN = 1;
MAX_NUM_CLUSTER_EVO2_FRNN = 3;
MIN_NUM_CLUSTER_EVO2_FRNN = 1;
MAX_NUM_CLUSTER_MEM_PPARA_EVO2_FRNN = 9;
NUM_CLASS_EVO2_FRNN = 3;
MAX_NUM_FUZZY_RULE_EVO2_FRNN = (2 * N_INPUT_EVO2_FRNN + 1);
DIM_CLUSTER_BIN_RULE_EVO2_FRNN = (MAX_NUM_FUZZY_RULE_EVO2_FRNN * N_INPUT_EVO2_FRNN);
DIM_CLUSTER_MEM_EVO2_FRNN = (N_INPUT_EVO2_FRNN * MAX_NUM_CLUSTER_EVO2_FRNN);
DIM_CLUSTER_MEM_TYPE_EVO2_FRNN = DIM_CLUSTER_MEM_EVO2_FRNN;
DIM_CLUSTER_MEM_PARA_EVO2_FRNN = (MAX_NUM_CLUSTER_MEM_PPARA_EVO2_FRNN * DIM_CLUSTER_MEM_EVO2_FRNN);
DIM_FUZZY_BIN_ROUGH_EVO2_FRNN = (NUM_CLASS_EVO2_FRNN * MAX_NUM_FUZZY_RULE_EVO2_FRNN);
DIM_FUZZY_ROUGH_MEM_PARA_EVO2_FRNN = (NUM_CLASS_EVO2_FRNN * MAX_NUM_FUZZY_RULE_EVO2_FRNN);
NUM_PARA_CONSE_EVO2_FRNN = (N_INPUT_EVO2_FRNN + 1);
DIM_CONSEQUENCE_EVO2_FRNN = (NUM_CLASS_EVO2_FRNN * NUM_PARA_CONSE_EVO2_FRNN);

DIM_EVO2_FRNN = (DIM_CLUSTER_MEM_TYPE_EVO2_FRNN + DIM_CLUSTER_BIN_RULE_EVO2_FRNN + DIM_FUZZY_BIN_ROUGH_EVO2_FRNN + DIM_CLUSTER_MEM_PARA_EVO2_FRNN + DIM_FUZZY_ROUGH_MEM_PARA_EVO2_FRNN + DIM_CONSEQUENCE_EVO2_FRNN);
DIM_OBJ_EVO2_FRNN = 2;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%EVO3_FRNN - fuzzy rough neural network
N_INPUT_EVO3_FRNN = 3;
N_IN_RSD_EVO3_FRNN = (N_INPUT_EVO3_FRNN - 1);
N_OUTPUT_EVO3_FRNN = 1;
MAX_NUM_CLUSTER_EVO3_FRNN = 3;
MIN_NUM_CLUSTER_EVO3_FRNN = 1;
MAX_NUM_CLUSTER_MEM_PPARA_EVO3_FRNN = 9;
NUM_CLASS_EVO3_FRNN = 3;
MAX_NUM_FUZZY_RULE_EVO3_FRNN = (2 * N_INPUT_EVO3_FRNN + 1);
DIM_CLUSTER_BIN_RULE_EVO3_FRNN = (MAX_NUM_FUZZY_RULE_EVO3_FRNN * N_INPUT_EVO3_FRNN);
DIM_CLUSTER_MEM_EVO3_FRNN = (N_INPUT_EVO3_FRNN * MAX_NUM_CLUSTER_EVO3_FRNN);
DIM_CLUSTER_MEM_TYPE_EVO3_FRNN = DIM_CLUSTER_MEM_EVO3_FRNN;
DIM_CLUSTER_MEM_PARA_EVO3_FRNN = (MAX_NUM_CLUSTER_MEM_PPARA_EVO3_FRNN * DIM_CLUSTER_MEM_EVO3_FRNN);
DIM_FUZZY_BIN_ROUGH_EVO3_FRNN = (NUM_CLASS_EVO3_FRNN * MAX_NUM_FUZZY_RULE_EVO3_FRNN);
DIM_FUZZY_ROUGH_MEM_PARA_EVO3_FRNN = (NUM_CLASS_EVO3_FRNN * MAX_NUM_FUZZY_RULE_EVO3_FRNN);

DIM_EVO3_FRNN = (DIM_CLUSTER_MEM_TYPE_EVO3_FRNN + DIM_CLUSTER_BIN_RULE_EVO3_FRNN + DIM_FUZZY_BIN_ROUGH_EVO3_FRNN + DIM_CLUSTER_MEM_PARA_EVO3_FRNN + DIM_FUZZY_ROUGH_MEM_PARA_EVO3_FRNN + NUM_CLASS_EVO3_FRNN);
DIM_OBJ_EVO3_FRNN = 2;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%EVO4_FRNN - fuzzy rough neural network
N_INPUT_EVO4_FRNN = 3;
N_IN_RSD_EVO4_FRNN = (N_INPUT_EVO4_FRNN - 1);
N_OUTPUT_EVO4_FRNN = 1;
MAX_NUM_CLUSTER_EVO4_FRNN = 3;
MIN_NUM_CLUSTER_EVO4_FRNN = 1;
MAX_NUM_CLUSTER_MEM_PPARA_EVO4_FRNN = 9;
NUM_CLASS_EVO4_FRNN = 3;
MAX_NUM_FUZZY_RULE_EVO4_FRNN = (2 * N_INPUT_EVO4_FRNN + 1);
DIM_CLUSTER_BIN_RULE_EVO4_FRNN = (MAX_NUM_FUZZY_RULE_EVO4_FRNN * N_INPUT_EVO4_FRNN);
DIM_CLUSTER_MEM_EVO4_FRNN = (N_INPUT_EVO4_FRNN * MAX_NUM_CLUSTER_EVO4_FRNN);
DIM_CLUSTER_MEM_TYPE_EVO4_FRNN = DIM_CLUSTER_MEM_EVO4_FRNN;
DIM_CLUSTER_MEM_PARA_EVO4_FRNN = (MAX_NUM_CLUSTER_MEM_PPARA_EVO4_FRNN * DIM_CLUSTER_MEM_EVO4_FRNN);
DIM_FUZZY_BIN_ROUGH_EVO4_FRNN = (NUM_CLASS_EVO4_FRNN * MAX_NUM_FUZZY_RULE_EVO4_FRNN);
DIM_FUZZY_ROUGH_MEM_PARA_EVO4_FRNN = (NUM_CLASS_EVO4_FRNN * MAX_NUM_FUZZY_RULE_EVO4_FRNN);
NUM_PARA_CONSE_EVO4_FRNN = (N_INPUT_EVO4_FRNN + 1);
DIM_CONSEQUENCE_EVO4_FRNN = (NUM_CLASS_EVO4_FRNN * NUM_PARA_CONSE_EVO4_FRNN);

DIM_EVO4_FRNN = (DIM_CLUSTER_MEM_TYPE_EVO4_FRNN + DIM_CLUSTER_BIN_RULE_EVO4_FRNN + DIM_FUZZY_BIN_ROUGH_EVO4_FRNN + DIM_CLUSTER_MEM_PARA_EVO4_FRNN + DIM_FUZZY_ROUGH_MEM_PARA_EVO4_FRNN + DIM_CONSEQUENCE_EVO4_FRNN);
DIM_OBJ_EVO4_FRNN = 2;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%EVO5_FRNN - fuzzy rough neural network
N_INPUT_EVO5_FRNN = 3;
N_IN_RSD_EVO5_FRNN = (N_INPUT_EVO5_FRNN - 1);
N_OUTPUT_EVO5_FRNN = 1;
MAX_NUM_CLUSTER_EVO5_FRNN = 3;
MIN_NUM_CLUSTER_EVO5_FRNN = 1;
MAX_NUM_CLUSTER_MEM_PPARA_EVO5_FRNN = (9 + 1);
NUM_CLASS_EVO5_FRNN = 3;
MAX_NUM_FUZZY_RULE_EVO5_FRNN = (2 * N_INPUT_EVO5_FRNN + 1);
DIM_CLUSTER_BIN_RULE_EVO5_FRNN = (MAX_NUM_FUZZY_RULE_EVO5_FRNN * N_INPUT_EVO5_FRNN);
DIM_CLUSTER_MEM_EVO5_FRNN = (N_INPUT_EVO5_FRNN * MAX_NUM_CLUSTER_EVO5_FRNN);
DIM_CLUSTER_MEM_TYPE_EVO5_FRNN = DIM_CLUSTER_MEM_EVO5_FRNN;
DIM_CLUSTER_MEM_PARA_EVO5_FRNN = (MAX_NUM_CLUSTER_MEM_PPARA_EVO5_FRNN * DIM_CLUSTER_MEM_EVO5_FRNN);
DIM_FUZZY_BIN_ROUGH_EVO5_FRNN = (NUM_CLASS_EVO5_FRNN * MAX_NUM_FUZZY_RULE_EVO5_FRNN);
DIM_FUZZY_ROUGH_MEM_PARA_EVO5_FRNN = (NUM_CLASS_EVO5_FRNN * MAX_NUM_FUZZY_RULE_EVO5_FRNN);
NUM_PARA_CONSE_EVO5_FRNN = (N_INPUT_EVO5_FRNN + 1);
DIM_CONSEQUENCE_EVO5_FRNN = (NUM_CLASS_EVO5_FRNN * (2 * NUM_PARA_CONSE_EVO5_FRNN));
DIM_CONSE_WEIGHT_EVO5_FRNN = 0;

DIM_EVO5_FRNN = (DIM_CLUSTER_MEM_TYPE_EVO5_FRNN + DIM_CLUSTER_BIN_RULE_EVO5_FRNN + DIM_FUZZY_BIN_ROUGH_EVO5_FRNN + DIM_CLUSTER_MEM_PARA_EVO5_FRNN + DIM_FUZZY_ROUGH_MEM_PARA_EVO5_FRNN + DIM_CONSEQUENCE_EVO5_FRNN + DIM_CONSE_WEIGHT_EVO5_FRNN);
DIM_OBJ_EVO5_FRNN = 2;

%%
MF_type_start_ind = 0;
MF_type_end_ind = 0;
MF_para_start_ind = 0;
MF_para_end_ind = 0;
switch FRNNtype
    case 'FRNN1'
        MF_type_start_ind = 1;
        MF_type_end_ind = DIM_CLUSTER_MEM_TYPE_EVO1_FRNN;
        MF_para_start_ind = DIM_CLUSTER_MEM_TYPE_EVO1_FRNN + DIM_CLUSTER_BIN_RULE_EVO1_FRNN + DIM_FUZZY_BIN_ROUGH_EVO1_FRNN + DIM_CLUSTER_MEM_PARA_EVO1_FRNN + DIM_FUZZY_ROUGH_MEM_PARA_EVO1_FRNN + NUM_CLASS_EVO1_FRNN

end

